import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tw from "tailwind-styled-components"


export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Uber Clone Pr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Map >
        Map
      </Map>
      <ActionItems>
        Start
      </ActionItems>
    </Wrapper>
  )
}

const Wrapper = tw.div `

`

const Map = tw.div `

`

const ActionItems = tw.div `

`